version: '3.9'
services:
  go-tms-pg:
    container_name: "go-tms-pg"
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: go-tms-pg
    ports:
      - "5432:5432"
    volumes:
      - ./data:/var/lib/postgresql/data